# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            # n'active le firewall qu'au besoin (nouveau comportement Symfony 6+)
            lazy: true

            # provider singulier
            provider: app_user_provider

            # formulaire de connexion
            form_login:
                login_path:  /login
                check_path:  /login

                username_parameter: email
                password_parameter: password
                 # redirige vers /login après un succès d'authent
                default_target_path: login
                always_use_default_target_path: true
            # déconnexion
            logout:
                path:   /logout
                target: /login

    access_control:
        # 1) login & register en accès public
        - { path: ^/(login|register)$, roles: PUBLIC_ACCESS }

        # 2) tout le reste du site requiert au minimum ROLE_USER
        - { path: ^/,              roles: ROLE_USER }
