security:
    encoders:
        App\Entity\User:
            algorithm: auto    # utilise l'algorithme de hashage le plus robuste automatiquement:contentReference[oaicite:6]{index=6}

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # on charge l'utilisateur via son email:contentReference[oaicite:7]{index=7}

    firewalls:
        # Firewall dev (Symfony profiler, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            anonymous: true              # permet aux non-connectés d'accéder aux pages publiques
            provider: app_user_provider  # utilise le provider déclaré ci-dessus
            form_login:
                login_path: app_login    # route name pour afficher le formulaire de login
                check_path: app_login    # route name identique pour traiter le login (POST)
                username_parameter: email    # nom du champ email dans le form de login:contentReference[oaicite:8]{index=8}
                password_parameter: password # nom du champ mot de passe (par défaut "password")
                default_target_path: app_home # page de destination après succès (exemple)
                enable_csrf: true        # protection CSRF du formulaire (recommandé)
            logout:
                path: app_logout         # route de déconnexion (assurez-vous qu’elle existe)

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }  # tout le reste nécessite d'être connecté
