security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            # attention : ceci n'est PAS un tableau !
            provider: app_user_provider
            lazy: true

            form_login:
                login_path:        login
                check_path:        login
                username_parameter: _username
                password_parameter: _password
                csrf_parameter:     _csrf_token   # nom du champ _csrf_token dans votre form
                csrf_token_id:      authenticate  # idem, pour le csrf_token() dans Twig
                enable_csrf:        true

                default_target_path:           app_appointment_index
                always_use_default_target_path: true

            logout:
                path:   logout
                target: login

    access_control:
        - { path: ^/(login|register)$, roles: PUBLIC_ACCESS }
        - { path: ^/appointment/\d+/edit$, roles: [ROLE_ADMIN, ROLE_DOCTOR] }
        - { path: ^/, roles: ROLE_USER }
